spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backoffice
    username: root
    password:
  batch:
    initialize-schema: always
  jpa:
    show-sql: true
    open-in-view: false

backoffice:
  brands-watch-directory: /tmp/backoffice/brands
  inventories-watch-directory: /tmp/backoffice/inventories